### ISSUE TITLE
Question on the natural language description of `HPW#2`

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs492-fall23#12]
Hi, I have a question regarding the natural language description of `HPW(High Priority of Writer)2`.

I came to wonder that an execution trace `ir1, ww, ir2, rs2` is be treated differently in: LTS and natural language describing `HPW2`.

- With regards to the original intention, in LTS

<img width="906" alt="image" src="https://github.com/swtv-kaist/cs492-fall23/assets/44872014/5f62db1c-a74c-4b19-8025-131f53bbca8b">

I believe that the original intention of `HPW2` reflected in the LTS does **NOT allow** `ir1, ww, ir2, rs2`,
for it doesn't include such an execution trace.

- With regards to the natural language description

It says,

<img width="854" alt="image" src="https://github.com/swtv-kaist/cs492-fall23/assets/44872014/0958faa2-09cb-4df9-94ae-5fbf81afd19d">

I think this is **allowed** in the natural language description of `HPW2` because:
before writer tries to write (corresponds to `ww`), reader 1 has been waiting to read CDA (`ir1`), so the HPW2 rule cannot be applied.
i.e., writer CANNOT hold a higher priority and thus reader 2 who comes afterwards (`ir2`) can freely read (`rs2`) before the writer writes.

I am a bit confused with the seemingly different interpretations of `HPW2`: one in LTS and one in natural language. Which should be taken as a correct interpretation of `HPW2`?

**Comment by swtv-kaist** [comment]
Hi, Jaehyun.  
Thank you for your sharp question for HW#2.

I agree with your interpretation of HPW#2 (i.e., according to the English description, ```ir1, ww, ir2, rs2``` should be accepted; ```rs2``` can occur before ```ws``` because ```ir1``` occured before ```ww```),  although that was not my intention for HPW#2.   
I fixed the English description of HPW#2 by adding sub-condition B as follows and uploaded it to the CS492B home page.
(my mistake clearly shows the benefit of formal specification ;-) 
![image](https://github.com/swtv-kaist/cs492-fall23/assets/29851315/d5dea93c-bdf0-45d2-984b-647ac32eb4ae)

Thank you again for your finding of incorrect description of HPW#2.

**Comment by jaehyun1ee** [comment]
Thank you for the edits, professor :)

**Comment by yheechan** [comment]
> Hi, Jaehyun. Thank you for your sharp question for HW#2.
> 
> I agree with your interpretation of HPW#2 (i.e., according to the English description, `ir1, ww, ir2, rs2` should be accepted; `rs2` can occur before `ws` because `ir1` occured before `ww`), although that was not my intention for HPW#2. I fixed the English description of HPW#2 by adding sub-condition B as follows and uploaded it to the CS492B home page. (my mistake clearly shows the benefit of formal specification ;-) ![image](https://user-images.githubusercontent.com/29851315/283099059-d5dea93c-bdf0-45d2-984b-647ac32eb4ae.png)
> 
> Thank you again for your finding of incorrect description of HPW#2.

Hello, I have a follow up question regarding state B, "`Ri` is waiting to read CDA before T, `Ri` may read CDA before W writes to CDA".

Wouldn't `ir1, ww, ir2, rs2` be restricted because `rs2` is not of `ir1` (i.e. reader 1 is not reader 2)?
In this case (`ir, ww, ir2, rs2`), **reader 1** is waiting to read CDA before T, henseforth, **reader 1** may read CDA before W writes (not reader 2).
